version: "3.8"

services:
  kafka:
    image: bashj79/kafka-kraft:latest
    container_name: kafka-erik
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
